"use strict";
const $=s=>document.querySelector(s), state={records:[],active:null,preview:false,poll:null,job:null}, sourceIndex=new Map();
async function api(path,options={}){const r=await fetch(path,{cache:"no-store",...options});if(!r.ok)throw new Error((await r.text()).trim()||`Request failed (${r.status})`);return r.json()}
function duration(v){v=Math.max(0,v||0);return `${Math.floor(v/60)}:${Math.floor(v%60).toString().padStart(2,"0")}`}
function date(v){return new Intl.DateTimeFormat(undefined,{month:"short",day:"numeric",hour:"2-digit",minute:"2-digit"}).format(new Date(v))}
function setStatus(text,bad=false){const n=$("#status");n.textContent=text;n.className="status"+(bad?" error":"")}

const components={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16}, sizes={5121:1,5123:2,5125:4,5126:4};
function glbDocument(buffer){
  const view=new DataView(buffer);if(view.getUint32(0,true)!==0x46546c67||view.getUint32(4,true)!==2)throw new Error("Not a GLB v2 file");
  const jsonLength=view.getUint32(12,true);const root=JSON.parse(new TextDecoder().decode(new Uint8Array(buffer,20,jsonLength)));
  const binHeader=20+jsonLength;if(view.getUint32(binHeader+4,true)!==0x004e4942)throw new Error("GLB has no binary chunk");const binary=binHeader+8;
  const accessor=(index,normalized=false)=>{const a=root.accessors[index],b=root.bufferViews[a.bufferView],count=a.count,n=components[a.type],size=sizes[a.componentType],stride=b.byteStride||n*size,offset=binary+(b.byteOffset||0)+(a.byteOffset||0);if(!n||!size)throw new Error("Unsupported accessor");
    const convert=normalized&&a.componentType!==5126,max=a.componentType===5121?255:a.componentType===5123?65535:4294967295;
    const out=a.componentType===5126||convert?new Float32Array(count*n):a.componentType===5125?new Uint32Array(count*n):a.componentType===5123?new Uint16Array(count*n):new Uint8Array(count*n);
    for(let i=0;i<count;i++)for(let j=0;j<n;j++){const p=offset+i*stride+j*size,v=a.componentType===5126?view.getFloat32(p,true):a.componentType===5125?view.getUint32(p,true):a.componentType===5123?view.getUint16(p,true):view.getUint8(p);out[i*n+j]=convert?v/max:v}return out};return{root,accessor}}
function sceneNodes(root){const nodes=(root.nodes||[]).map(n=>({name:n.name||"",t:new Float32Array(n.translation||[0,0,0]),r:new Float32Array(n.rotation||[0,0,0,1]),s:new Float32Array(n.scale||[1,1,1]),matrix:n.matrix?new Float32Array(n.matrix):null,children:n.children||[],mesh:n.mesh}));const parents=new Int32Array(nodes.length).fill(-1);nodes.forEach((n,i)=>n.children.forEach(c=>parents[c]=i));return{nodes,parents}}
function animation(root,accessor){const clips=[];for(const channel of root.animations?.[0]?.channels||[]){const sampler=root.animations[0].samplers[channel.sampler];clips.push({node:channel.target.node,path:channel.target.path,times:accessor(sampler.input),values:accessor(sampler.output)})}let duration=0;clips.forEach(c=>{if(c.times.length)duration=Math.max(duration,c.times[c.times.length-1])});return{clips,duration}}
function identities(count){const out=new Float32Array(count*16);for(let i=0;i<count;i++)out.set(identity(),i*16);return out}
function influences(vertices){const joints=new Uint16Array(vertices*4),weights=new Float32Array(vertices*4);for(let i=0;i<vertices;i++)weights[i*4]=1;return{joints,weights}}
function parseBoundGLB(buffer){const{root,accessor}=glbDocument(buffer);
  const skin=root.skins?.[0];if(!skin)throw new Error("GLB has no skin");const meshNode=root.nodes.findIndex(n=>n.skin===0&&n.mesh!==undefined);if(meshNode<0)throw new Error("GLB has no skinned mesh node");
  const primitive=root.meshes[root.nodes[meshNode].mesh].primitives[0],attrs=primitive.attributes;
  const positions=accessor(attrs.POSITION),{nodes,parents}=sceneNodes(root),motion=animation(root,accessor);
  return {positions,normals:attrs.NORMAL===undefined?new Float32Array(positions.length):accessor(attrs.NORMAL),colors:attrs.COLOR_0===undefined?null:accessor(attrs.COLOR_0,true),joints:accessor(attrs.JOINTS_0),weights:accessor(attrs.WEIGHTS_0),indices:primitive.indices===undefined?Uint32Array.from({length:positions.length/3},(_,i)=>i):accessor(primitive.indices),inverse:accessor(skin.inverseBindMatrices),jointNodes:skin.joints,nodes,parents,...motion,meshNode,hasMesh:true,hasSkeleton:true};
}

function identity(){return new Float32Array([1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1])}
function multiply(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let v=0;for(let k=0;k<4;k++)v+=a[k*4+r]*b[c*4+k];o[c*4+r]=v}return o}
function compose(t,q,s){const [x,y,z,w]=q,x2=x+x,y2=y+y,z2=z+z,xx=x*x2,xy=x*y2,xz=x*z2,yy=y*y2,yz=y*z2,zz=z*z2,wx=w*x2,wy=w*y2,wz=w*z2;return new Float32Array([(1-(yy+zz))*s[0],(xy+wz)*s[0],(xz-wy)*s[0],0,(xy-wz)*s[1],(1-(xx+zz))*s[1],(yz+wx)*s[1],0,(xz+wy)*s[2],(yz-wx)*s[2],(1-(xx+yy))*s[2],0,t[0],t[1],t[2],1])}
function nodeMatrix(node){return node.matrix||compose(node.t,node.r,node.s)}
function parseMeshGLB(buffer){const{root,accessor}=glbDocument(buffer),scene=sceneNodes(root),meshNode=scene.nodes.findIndex(n=>n.mesh!==undefined);if(meshNode<0)throw new Error("GLB has no mesh");const primitive=root.meshes[scene.nodes[meshNode].mesh]?.primitives?.find(p=>p.attributes?.POSITION!==undefined);if(!primitive)throw new Error("GLB has no triangle positions");const attrs=primitive.attributes,source=accessor(attrs.POSITION),global=[];const get=i=>global[i]||(global[i]=scene.parents[i]<0?nodeMatrix(scene.nodes[i]):multiply(get(scene.parents[i]),nodeMatrix(scene.nodes[i]))),world=get(meshNode),positions=new Float32Array(source.length);for(let i=0;i<source.length;i+=3){const x=source[i],y=source[i+1],z=source[i+2];positions[i]=world[0]*x+world[4]*y+world[8]*z+world[12];positions[i+1]=world[1]*x+world[5]*y+world[9]*z+world[13];positions[i+2]=world[2]*x+world[6]*y+world[10]*z+world[14]}let normals;if(attrs.NORMAL===undefined)normals=new Float32Array(source.length);else{const input=accessor(attrs.NORMAL);normals=new Float32Array(input.length);for(let i=0;i<input.length;i+=3){const value=normalize([world[0]*input[i]+world[4]*input[i+1]+world[8]*input[i+2],world[1]*input[i]+world[5]*input[i+1]+world[9]*input[i+2],world[2]*input[i]+world[6]*input[i+1]+world[10]*input[i+2]]);normals.set(value,i)}}const indices=primitive.indices===undefined?Uint32Array.from({length:positions.length/3},(_,i)=>i):accessor(primitive.indices),skin=influences(positions.length/3);return{positions,normals,colors:attrs.COLOR_0===undefined?null:accessor(attrs.COLOR_0,true),indices,...skin,inverse:identities(1),jointNodes:[0],nodes:[{t:new Float32Array(3),r:new Float32Array([0,0,0,1]),s:new Float32Array([1,1,1]),matrix:null,children:[]}],parents:new Int32Array([-1]),clips:[],duration:0,meshNode:0,hasMesh:true,hasSkeleton:false}}
function parseMotionGLB(buffer){const{root,accessor}=glbDocument(buffer),{nodes,parents}=sceneNodes(root),motion=animation(root,accessor);if(!nodes.length||!motion.clips.length)throw new Error("GLB has no skeleton animation");const jointNodes=root.skins?.[0]?.joints||nodes.map((_,i)=>i).filter(i=>nodes[i].mesh===undefined);if(!jointNodes.length)throw new Error("GLB has no skeleton nodes");return{positions:new Float32Array(),normals:new Float32Array(),colors:null,joints:new Uint16Array(),weights:new Float32Array(),indices:new Uint32Array(),inverse:identities(jointNodes.length),jointNodes,nodes,parents,...motion,meshNode:-1,hasMesh:false,hasSkeleton:true}}
function combineInputs(mesh,motion){if(!mesh?.hasMesh)return motion;const skin=influences(mesh.positions.length/3);return{...motion,positions:mesh.positions,normals:mesh.normals,colors:mesh.colors,indices:mesh.indices,...skin,hasMesh:true,hasSkeleton:true}}
function perspective(fov,aspect,near,far){const f=1/Math.tan(fov/2),nf=1/(near-far);return new Float32Array([f/aspect,0,0,0,0,f,0,0,0,0,(far+near)*nf,-1,0,0,2*far*near*nf,0])}
function normalize(v){const l=Math.hypot(...v)||1;return v.map(x=>x/l)}function cross(a,b){return[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]]}
function lookAt(eye,target,up){const z=normalize(eye.map((v,i)=>v-target[i])),x=normalize(cross(up,z)),y=cross(z,x);return new Float32Array([x[0],y[0],z[0],0,x[1],y[1],z[1],0,x[2],y[2],z[2],0,-x.reduce((v,n,i)=>v+n*eye[i],0),-y.reduce((v,n,i)=>v+n*eye[i],0),-z.reduce((v,n,i)=>v+n*eye[i],0),1])}
function slerp(a,b,t){let dot=a[0]*b[0]+a[1]*b[1]+a[2]*b[2]+a[3]*b[3],bb=b;if(dot<0){dot=-dot;bb=[-b[0],-b[1],-b[2],-b[3]]}if(dot>.9995)return normalize(a.map((v,i)=>v+(bb[i]-v)*t));const th=Math.acos(Math.min(1,dot)),s=Math.sin(th);return a.map((v,i)=>(v*Math.sin((1-t)*th)+bb[i]*Math.sin(t*th))/s)}

class Viewer{
  constructor(canvas){this.canvas=canvas;this.gl=canvas.getContext("webgl2",{antialias:true});if(!this.gl)throw new Error("WebGL 2 is required");this.data=null;this.selectedMesh=null;this.staticMesh=false;this.time=0;this.playing=true;this.restPose=new URLSearchParams(location.search).has("rest");this.yaw=.65;this.pitch=.28;this.distance=3;this.target=[0,0,0];this.baseTarget=[0,0,0];this.desiredTarget=[0,0,0];this.skeletonTarget=[0,0,0];this.desiredSkeletonTarget=[0,0,0];this.pointer={inside:false,x:0,y:0};this.hoveredJoint=-1;this.lockedJoint=-1;this.jointScreens=[];this.radius=1;this.last=performance.now();this.init();this.controls();new ResizeObserver(()=>this.resize()).observe(canvas);requestAnimationFrame(t=>this.frame(t))}
  shader(type,source){const g=this.gl,s=g.createShader(type);g.shaderSource(s,source);g.compileShader(s);if(!g.getShaderParameter(s,g.COMPILE_STATUS))throw new Error(g.getShaderInfoLog(s));return s}
  init(){const g=this.gl,vs=`#version 300 es
  precision highp float;precision highp sampler2D;layout(location=0)in vec3 p;layout(location=1)in vec3 n;layout(location=2)in uvec4 j;layout(location=3)in vec4 w;layout(location=4)in vec4 c;uniform mat4 mvp;uniform sampler2D boneTex;uniform int selectedJoint;out vec3 normal;out vec3 world;out vec4 tint;out float heat;
  mat4 bone(uint i){int x=int(i)*4;return mat4(texelFetch(boneTex,ivec2(x,0),0),texelFetch(boneTex,ivec2(x+1,0),0),texelFetch(boneTex,ivec2(x+2,0),0),texelFetch(boneTex,ivec2(x+3,0),0));}
  void main(){mat4 s=w.x*bone(j.x)+w.y*bone(j.y)+w.z*bone(j.z)+w.w*bone(j.w);vec4 q=s*vec4(p,1);world=q.xyz;normal=mat3(s)*n;tint=c;heat=0.;if(selectedJoint>=0){uint target=uint(selectedJoint);heat=(j.x==target?w.x:0.)+(j.y==target?w.y:0.)+(j.z==target?w.z:0.)+(j.w==target?w.w:0.);}gl_Position=mvp*q;}`,
  fs=`#version 300 es
  precision highp float;in vec3 normal;in vec3 world;in vec4 tint;in float heat;out vec4 color;
  vec3 linearToSrgb(vec3 v){vec3 lo=12.92*v,hi=1.055*pow(max(v,vec3(0.)),vec3(1./2.4))-.055;return mix(hi,lo,lessThanEqual(v,vec3(.0031308)));}
  void main(){vec3 n=normalize(normal),l=normalize(vec3(.4,.85,.55));float d=.28+max(dot(n,l),0.)*.72;float rim=pow(1.-max(dot(n,normalize(vec3(.2,.15,1.))),0.),2.);float red=1.-exp(-6.*clamp(heat,0.,1.));vec3 base=mix(tint.rgb,vec3(1.,.015,.008),red);vec3 lit=base*d+rim*vec3(.08,.06,.12);color=vec4(linearToSrgb(lit),tint.a);}`;
    this.program=g.createProgram();g.attachShader(this.program,this.shader(g.VERTEX_SHADER,vs));g.attachShader(this.program,this.shader(g.FRAGMENT_SHADER,fs));g.linkProgram(this.program);if(!g.getProgramParameter(this.program,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(this.program));this.mvp=g.getUniformLocation(this.program,"mvp");this.boneTex=g.getUniformLocation(this.program,"boneTex");this.selectedJoint=g.getUniformLocation(this.program,"selectedJoint");this.boneTexture=g.createTexture();this.vao=g.createVertexArray();this.buffers=[0,1,2,3,4,5].map(()=>g.createBuffer());
    const skeletonVS=`#version 300 es
    precision highp float;layout(location=0)in vec3 p;uniform mat4 mvp;uniform float pointSize;void main(){gl_Position=mvp*vec4(p,1);gl_PointSize=pointSize;}`,
    skeletonFS=`#version 300 es
    precision highp float;uniform vec4 ink;out vec4 color;void main(){color=ink;}`;
    this.skeletonProgram=g.createProgram();g.attachShader(this.skeletonProgram,this.shader(g.VERTEX_SHADER,skeletonVS));g.attachShader(this.skeletonProgram,this.shader(g.FRAGMENT_SHADER,skeletonFS));g.linkProgram(this.skeletonProgram);if(!g.getProgramParameter(this.skeletonProgram,g.LINK_STATUS))throw new Error(g.getProgramInfoLog(this.skeletonProgram));this.skeletonMvp=g.getUniformLocation(this.skeletonProgram,"mvp");this.skeletonInk=g.getUniformLocation(this.skeletonProgram,"ink");this.skeletonPointSize=g.getUniformLocation(this.skeletonProgram,"pointSize");this.skeletonVao=g.createVertexArray();this.skeletonBuffer=g.createBuffer();g.bindVertexArray(this.skeletonVao);g.bindBuffer(g.ARRAY_BUFFER,this.skeletonBuffer);g.enableVertexAttribArray(0);g.vertexAttribPointer(0,3,g.FLOAT,false,0,0);g.enable(g.DEPTH_TEST);g.enable(g.CULL_FACE);g.enable(g.BLEND);g.blendFunc(g.SRC_ALPHA,g.ONE_MINUS_SRC_ALPHA)}
  controls(){let drag=false,x=0,y=0;const pointer=e=>{const r=this.canvas.getBoundingClientRect();this.pointer={inside:true,x:e.clientX-r.left,y:e.clientY-r.top}};this.canvas.onpointerdown=e=>{pointer(e);drag=true;x=e.clientX;y=e.clientY;this.canvas.setPointerCapture(e.pointerId)};this.canvas.onpointermove=e=>{pointer(e);if(!drag)return;this.yaw+=(e.clientX-x)*.008;this.pitch=Math.max(-1.2,Math.min(1.2,this.pitch+(e.clientY-y)*.008));x=e.clientX;y=e.clientY};this.canvas.onpointerup=()=>drag=false;this.canvas.onpointerleave=()=>{if(!drag){this.pointer.inside=false;this.clearHover()}};this.canvas.onwheel=e=>{e.preventDefault();this.distance=Math.max(this.radius*1.1,Math.min(this.radius*14,this.distance*Math.exp(e.deltaY*.001)))}}
  resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(this.canvas.clientWidth*d)),h=Math.max(1,Math.floor(this.canvas.clientHeight*d));if(this.canvas.width!==w||this.canvas.height!==h){this.canvas.width=w;this.canvas.height=h}}
  reset(){this.yaw=.65;this.pitch=.28;this.distance=this.radius*2.8}
  async load(url){const r=await fetch(url,{cache:"no-store"});if(!r.ok)throw new Error("Could not load output GLB");this.setData(parseBoundGLB(await r.arrayBuffer()),false);this.selectedMesh=this.data}
  showMesh(buffer){const mesh=parseMeshGLB(buffer);this.selectedMesh=mesh;this.setData(mesh,true)}
  showMotion(buffer){const motion=parseMotionGLB(buffer);this.setData(combineInputs(this.selectedMesh,motion),true)}
  setData(data,staticMesh){this.data=data;this.staticMesh=staticMesh;this.lockedJoint=-1;this.clearHover();if(data.jointNodes.length*4>this.gl.getParameter(this.gl.MAX_TEXTURE_SIZE))throw new Error("Rig exceeds this GPU's bone-texture limit");this.weightStats=Array.from({length:data.jointNodes.length},()=>({max:0,count:0}));for(let i=0;i<data.weights.length;i++){const weight=data.weights[i],joint=data.joints[i],stat=this.weightStats[joint];if(stat&&weight>.001){stat.max=Math.max(stat.max,weight);stat.count++}}const query=new URLSearchParams(location.search),requested=Number(query.get("time")),requestedJoint=query.get("joint");this.time=Number.isFinite(requested)?Math.max(0,Math.min(data.duration,requested)):0;this.playing=data.duration>0&&!query.has("pause");this.restPose=false;if(requestedJoint){const exact=data.jointNodes.findIndex(node=>data.nodes[node].name===requestedJoint),suffix=data.jointNodes.findIndex(node=>data.nodes[node].name.endsWith(requestedJoint));this.lockedJoint=this.hoveredJoint=exact>=0?exact:suffix}this.fit();this.upload();$("#empty").hidden=true;const labels=$("#compareLabels"),both=data.hasMesh&&data.hasSkeleton;labels.hidden=false;labels.classList.toggle("single",!both);$("#meshLabel").textContent=data.hasMesh?(staticMesh?"Static mesh":"Animated mesh"):"";$("#skeletonLabel").textContent=data.hasSkeleton?`${staticMesh?"Kimodo driving skeleton":"Driving skeleton"} · hover a joint`:"";$("#meshLabel").hidden=!data.hasMesh;$("#skeletonLabel").hidden=!data.hasSkeleton;this.updateUI()}
  fit(){const d=this.data,global=new Array(d.nodes.length),get=i=>global[i]||(global[i]=d.parents[i]<0?nodeMatrix(d.nodes[i]):multiply(get(d.parents[i]),nodeMatrix(d.nodes[i]))),meshValues=Array.from(d.positions),skeletonValues=[];for(const node of d.jointNodes){const value=get(node);skeletonValues.push(value[12],value[13],value[14])}const measure=values=>{const lo=[Infinity,Infinity,Infinity],hi=[-Infinity,-Infinity,-Infinity];for(let i=0;i<values.length;i+=3)for(let a=0;a<3;a++){lo[a]=Math.min(lo[a],values[i+a]);hi[a]=Math.max(hi[a],values[i+a])}if(!Number.isFinite(lo[0])){lo.fill(-.5);hi.fill(.5)}return{target:lo.map((v,i)=>(v+hi[i])*.5),radius:Math.max(.01,Math.hypot(hi[0]-lo[0],hi[1]-lo[1],hi[2]-lo[2])*.5)}};const mesh=measure(meshValues),skeleton=measure(skeletonValues),all=measure([...meshValues,...skeletonValues]);this.meshTarget=mesh.target;this.meshRadius=mesh.radius;this.skeletonBaseTarget=skeleton.target;this.skeletonTarget=[...skeleton.target];this.desiredSkeletonTarget=[...skeleton.target];this.skeletonRadius=skeleton.radius;this.skeletonRootRest=d.jointNodes.length?Array.from(get(d.jointNodes[0]).slice(12,15)):[0,0,0];this.baseTarget=all.target;this.target=[...all.target];this.desiredTarget=[...all.target];this.radius=all.radius;this.reset()}
  upload(){const g=this.gl,d=this.data;g.bindVertexArray(this.vao);const bind=(i,data,size,type,integer=false)=>{g.bindBuffer(g.ARRAY_BUFFER,this.buffers[i]);g.bufferData(g.ARRAY_BUFFER,data,g.STATIC_DRAW);g.enableVertexAttribArray(i);integer?g.vertexAttribIPointer(i,size,type,0,0):g.vertexAttribPointer(i,size,type,false,0,0)};bind(0,d.positions,3,g.FLOAT);bind(1,d.normals,3,g.FLOAT);const jointType=d.joints instanceof Uint8Array?g.UNSIGNED_BYTE:d.joints instanceof Uint16Array?g.UNSIGNED_SHORT:null;if(jointType===null)throw new Error("GLB joint indices must be unsigned bytes or shorts");bind(2,d.joints,4,jointType,true);bind(3,d.weights,4,g.FLOAT);if(d.colors)bind(4,d.colors,4,g.FLOAT);else{g.disableVertexAttribArray(4);g.vertexAttrib4f(4,.25,.88,.76,1)}g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,this.buffers[5]);g.bufferData(g.ELEMENT_ARRAY_BUFFER,d.indices,g.STATIC_DRAW);this.indexType=d.indices instanceof Uint32Array?g.UNSIGNED_INT:d.indices instanceof Uint16Array?g.UNSIGNED_SHORT:g.UNSIGNED_BYTE;g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.boneTexture);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MIN_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_MAG_FILTER,g.NEAREST);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_S,g.CLAMP_TO_EDGE);g.texParameteri(g.TEXTURE_2D,g.TEXTURE_WRAP_T,g.CLAMP_TO_EDGE);g.texImage2D(g.TEXTURE_2D,0,g.RGBA32F,d.jointNodes.length*4,1,0,g.RGBA,g.FLOAT,null)}
  pose(){const d=this.data,trs=d.nodes.map(n=>({t:new Float32Array(n.t),r:new Float32Array(n.r),s:n.s,matrix:n.matrix}));for(const c of this.restPose?[]:d.clips){if(!c.times.length)continue;let hi=1;while(hi<c.times.length&&c.times[hi]<this.time)hi++;hi=Math.min(hi,c.times.length-1);const lo=Math.max(0,hi-1),span=c.times[hi]-c.times[lo],a=span>0?(this.time-c.times[lo])/span:0,n=c.path==="rotation"?4:3,A=Array.from(c.values.slice(lo*n,lo*n+n)),B=Array.from(c.values.slice(hi*n,hi*n+n));if(c.path==="rotation")trs[c.node].r=new Float32Array(slerp(A,B,a));else if(c.path==="translation")trs[c.node].t=new Float32Array(A.map((v,i)=>v+(B[i]-v)*a))}
    const global=new Array(d.nodes.length);const local=i=>trs[i].matrix&&d.clips.every(c=>c.node!==i)?trs[i].matrix:compose(trs[i].t,trs[i].r,trs[i].s),get=i=>global[i]||(global[i]=d.parents[i]<0?local(i):multiply(get(d.parents[i]),local(i))),rootNow=get(d.jointNodes[0]),offset=this.skeletonRootRest.map((v,i)=>rootNow[12+i]-v);if(this.staticMesh){this.desiredTarget=[...this.baseTarget];this.desiredSkeletonTarget=this.skeletonBaseTarget.map((v,i)=>v+offset[i])}else this.desiredTarget=this.baseTarget.map((v,i)=>v+offset[i]);const bones=new Float32Array(d.jointNodes.length*16),joints=new Float32Array(d.jointNodes.length*3);d.jointNodes.forEach((node,i)=>{const matrix=get(node);bones.set(multiply(matrix,d.inverse.slice(i*16,i*16+16)),i*16);joints.set(matrix.slice(12,15),i*3)});return {bones,joints}}
  updateUI(){const total=this.data?.duration||0;$("#timeline").value=total?this.time/total:0;$("#timeline").disabled=!total;$("#play").disabled=!total;$("#rest").disabled=!this.data?.hasSkeleton;$("#time").textContent=`${duration(this.time)} / ${duration(total)}`;$("#play").textContent=this.playing?"Pause":"Play";$("#rest").textContent=this.restPose?"Play motion":"Rest pose"}
  clearHover(){this.hoveredJoint=-1;$("#jointHover").hidden=true}
  updateHover(pose,view,x,width,height){const d=this.data,label=$("#jointHover"),sx=this.canvas.clientWidth/this.canvas.width,sy=this.canvas.clientHeight/height;this.jointScreens=d.jointNodes.map((_,i)=>{const px=pose.joints[i*3],py=pose.joints[i*3+1],pz=pose.joints[i*3+2],cx=view[0]*px+view[4]*py+view[8]*pz+view[12],cy=view[1]*px+view[5]*py+view[9]*pz+view[13],cw=view[3]*px+view[7]*py+view[11]*pz+view[15];return cw<=0?null:{x:(x+(cx/cw*.5+.5)*width)*sx,y:(1-(cy/cw*.5+.5))*height*sy}});const left=x*sx,right=(x+width)*sx;let best=this.lockedJoint;if(best<0){if(!d.hasSkeleton||!this.pointer.inside||this.pointer.x<left||this.pointer.x>right){this.clearHover();return}let distance=15*15;this.jointScreens.forEach((point,i)=>{if(!point)return;const dx=point.x-this.pointer.x,dy=point.y-this.pointer.y,value=dx*dx+dy*dy;if(value<distance){distance=value;best=i}})}this.hoveredJoint=best;if(best<0){label.hidden=true;return}const point=this.jointScreens[best],node=d.nodes[d.jointNodes[best]],stat=this.weightStats[best],detail=document.createElement("small");detail.textContent=d.hasMesh?`red = skin weight · max ${Math.round(stat.max*100)}% · ${stat.count.toLocaleString()} vertices`:"No bound mesh loaded";label.replaceChildren(document.createTextNode(node.name||`Joint ${best}`),detail);if(point){label.style.left=`${Math.max(4,Math.min(this.canvas.clientWidth-275,point.x))}px`;label.style.top=`${Math.max(20,Math.min(this.canvas.clientHeight-65,point.y))}px`}label.hidden=false}
  frame(now){const dt=Math.min(.1,(now-this.last)/1000);this.last=now;if(this.data&&this.playing&&this.data.duration){this.time=(this.time+dt)%this.data.duration;this.updateUI()}const follow=1-Math.exp(-dt*5);for(let i=0;i<3;i++){this.target[i]+=(this.desiredTarget[i]-this.target[i])*follow;this.skeletonTarget[i]+=(this.desiredSkeletonTarget[i]-this.skeletonTarget[i])*follow}this.resize();this.draw();requestAnimationFrame(t=>this.frame(t))}
  draw(){const g=this.gl,width=this.canvas.width,height=this.canvas.height;g.viewport(0,0,width,height);g.clearColor(.035,.05,.065,1);g.clear(g.COLOR_BUFFER_BIT|g.DEPTH_BUFFER_BIT);if(!this.data)return;const d=this.data,both=d.hasMesh&&d.hasSkeleton,meshWidth=both?Math.floor(width/2):d.hasMesh?width:0,skeletonX=both?meshWidth+1:0,skeletonWidth=d.hasSkeleton?(both?width-meshWidth-1:width):0,viewportWidth=Math.max(1,meshWidth||skeletonWidth),pose=this.pose(),camera=(target,radius)=>{const cp=Math.cos(this.pitch),distance=radius*this.distance/this.radius,eye=[target[0]+Math.sin(this.yaw)*cp*distance,target[1]+Math.sin(this.pitch)*distance,target[2]+Math.cos(this.yaw)*cp*distance];return multiply(perspective(Math.PI/4,viewportWidth/height,.01,radius*50+100),lookAt(eye,target,[0,1,0]))},shared=camera(this.target,this.radius),meshView=this.staticMesh?camera(this.meshTarget,this.meshRadius):shared,skeletonView=this.staticMesh?camera(this.skeletonTarget,this.skeletonRadius):shared;
    this.updateHover(pose,skeletonView,skeletonX,skeletonWidth,height);
    if(d.hasMesh){g.viewport(0,0,meshWidth,height);g.useProgram(this.program);g.uniformMatrix4fv(this.mvp,false,meshView);g.uniform1i(this.selectedJoint,this.hoveredJoint);g.activeTexture(g.TEXTURE0);g.bindTexture(g.TEXTURE_2D,this.boneTexture);g.texSubImage2D(g.TEXTURE_2D,0,0,0,d.jointNodes.length*4,1,g.RGBA,g.FLOAT,this.staticMesh?identities(d.jointNodes.length):pose.bones);g.uniform1i(this.boneTex,0);g.bindVertexArray(this.vao);g.drawElements(g.TRIANGLES,d.indices.length,this.indexType,0)}
    if(d.hasSkeleton){const nodeToJoint=new Map(d.jointNodes.map((node,index)=>[node,index])),lines=[];d.jointNodes.forEach((node,index)=>{const parent=nodeToJoint.get(d.parents[node]);if(parent===undefined)return;lines.push(...pose.joints.slice(parent*3,parent*3+3),...pose.joints.slice(index*3,index*3+3))});g.viewport(skeletonX,0,skeletonWidth,height);g.useProgram(this.skeletonProgram);g.uniformMatrix4fv(this.skeletonMvp,false,skeletonView);g.bindVertexArray(this.skeletonVao);g.bindBuffer(g.ARRAY_BUFFER,this.skeletonBuffer);g.bufferData(g.ARRAY_BUFFER,new Float32Array(lines),g.DYNAMIC_DRAW);g.uniform4f(this.skeletonInk,.23,.83,.82,1);g.uniform1f(this.skeletonPointSize,1);g.drawArrays(g.LINES,0,lines.length/3);g.bufferData(g.ARRAY_BUFFER,pose.joints,g.DYNAMIC_DRAW);g.uniform4f(this.skeletonInk,.37,.9,.68,1);g.uniform1f(this.skeletonPointSize,Math.min(devicePixelRatio||1,2)*7);g.drawArrays(g.POINTS,0,pose.joints.length/3);if(this.hoveredJoint>=0){g.uniform4f(this.skeletonInk,1,.12,.08,1);g.uniform1f(this.skeletonPointSize,Math.min(devicePixelRatio||1,2)*13);g.drawArrays(g.POINTS,this.hoveredJoint,1)}}
    if(both){g.enable(g.SCISSOR_TEST);g.scissor(meshWidth,0,1,height);g.clearColor(.18,.25,.29,1);g.clear(g.COLOR_BUFFER_BIT);g.disable(g.SCISSOR_TEST)}}
}

const viewer=new Viewer($("#view"));
async function sources(){const list=await api("/api/sources"),mesh=$("#meshSource"),motion=$("#motionSource");for(const item of list){sourceIndex.set(item.id,item);if(item.kind==="mesh"||item.kind==="motion"){const o=document.createElement("option");o.value=item.id;o.textContent=item.label?`${item.label} — ${item.name}`:item.name;(item.kind==="mesh"?mesh:motion).appendChild(o)}}const input=sourceIndex.get("giraffe-input"),result=sourceIndex.get("giraffe-result");if(input||result){$("#giraffeExample").hidden=false;$("#giraffeInput").hidden=!input;$("#giraffeResult").hidden=!result}}
function render(){const box=$("#history");box.textContent="";if(!state.records.length){box.textContent="No bindings yet";return}for(const r of state.records){const b=document.createElement("button");b.className="item "+r.state+(state.active===r.id?" active":"");const rig=r.targetRig==="mixamo52"?"Mixamo52":"SOMA30";b.innerHTML=`<b>${escapeHTML(r.meshName)}</b><small>${escapeHTML(r.motionName)} · ${rig} · ${date(r.createdAt)} · ${r.state}</small>${r.error?`<small>${escapeHTML(r.error.slice(-300))}</small>`:""}`;b.disabled=r.state!=="done";b.onclick=()=>select(r);box.appendChild(b)}}
function escapeHTML(v){const n=document.createElement("span");n.textContent=v;return n.innerHTML}
async function refresh(){state.records=await api("/api/history");render();const tracked=state.job&&state.records.find(r=>r.id===state.job);if(tracked?.state==="done"){state.job=null;clearTimeout(state.poll);await select(tracked);return}if(tracked?.state==="error"){state.job=null;clearTimeout(state.poll);setStatus(tracked.error||"Binding failed",true);return}if(!state.active&&!state.preview&&!state.job){const requested=new URLSearchParams(location.search).get("binding"),complete=state.records.find(r=>r.id===requested&&r.state==="done")||state.records.find(r=>r.state==="done");if(complete)void select(complete)}const pending=state.records.some(r=>["queued","remeshing","running"].includes(r.state));if(pending){const r=tracked||state.records.find(r=>r.state==="running")||state.records.find(r=>r.state==="remeshing")||state.records.find(r=>r.state==="queued");state.job=r.id;setStatus(r.state==="running"?"Predicting SkinTokens weights for "+r.meshName+"…":r.state==="remeshing"?"Remeshing "+r.meshName+" for animation…":"Queued…");clearTimeout(state.poll);state.poll=setTimeout(()=>refresh().catch(e=>setStatus(e.message,true)),1000)}else if(!$("#status").classList.contains("error")&&!state.active&&!state.preview)setStatus("Ready")}
let previewRequest=0;
async function preview(kind,load){const request=++previewRequest;state.active=null;state.preview=true;render();$("#download").hidden=true;setStatus(kind==="mesh"?"Loading static mesh preview…":"Loading Kimodo skeleton…");try{const buffer=await load();if(request!==previewRequest)return;if(kind==="mesh")viewer.showMesh(buffer);else viewer.showMotion(buffer);setStatus(kind==="mesh"?"Showing the selected mesh unanimated":"Playing the Kimodo skeleton; the selected mesh remains static")}catch(e){if(request===previewRequest)setStatus(e.message,true)}}
async function select(r){++previewRequest;state.active=r.id;state.preview=false;render();$("#targetRig").value=r.targetRig||"soma30";const download=$("#download");download.href=`/files/${r.id}/animation.glb`;download.hidden=false;setStatus("Loading preview…");try{await viewer.load(`/files/${r.id}/animation.glb`);const rig=(r.targetRig||"soma30")==="mixamo52"?"Mixamo52":"SOMA30";setStatus(r.learned?`Playing learned SkinTokens binding · ${rig}`:"Playing geometric diagnostic binding")}catch(e){setStatus(e.message,true)}}
async function example(id,rigged){const item=sourceIndex.get(id);if(!item)return;const request=++previewRequest;state.active=null;state.preview=true;render();const download=$("#download");download.hidden=!rigged;download.href=`/api/sources/${encodeURIComponent(id)}`;download.download="giraffe-skintokens.glb";setStatus(rigged?"Loading the official learned giraffe rig…":"Loading the official giraffe input…");try{const url=`/api/sources/${encodeURIComponent(id)}`;if(rigged)await viewer.load(url);else{const response=await fetch(url,{cache:"no-store"});if(!response.ok)throw new Error((await response.text()).trim()||"Could not load giraffe input");viewer.showMesh(await response.arrayBuffer())}if(request!==previewRequest)return;setStatus(rigged?"Showing the official upstream learned rig; hover its joints to inspect weights":"Showing the official upstream giraffe input mesh")}catch(e){if(request===previewRequest)setStatus(e.message,true)}}
$("#mesh").onchange=e=>{const file=e.target.files[0];$("#meshName").textContent=file?.name||"No upload selected";if(!file)return;$("#meshSource").value="";if(file.name.toLowerCase().endsWith(".glb"))void preview("mesh",()=>file.arrayBuffer());else{++previewRequest;state.active=null;state.preview=true;render();$("#download").hidden=true;setStatus("T2MESH preview is available after automatic remeshing")}};
$("#motion").onchange=e=>{const file=e.target.files[0];$("#motionName").textContent=file?.name||"No upload selected";if(!file)return;$("#motionSource").value="";void preview("motion",()=>file.arrayBuffer())};
$("#meshSource").onchange=e=>{const item=sourceIndex.get(e.target.value);if(!item)return;$("#mesh").value="";$("#meshName").textContent=item.name;if(item.name.toLowerCase().endsWith(".glb"))void preview("mesh",async()=>{const r=await fetch(`/api/sources/${encodeURIComponent(item.id)}`,{cache:"no-store"});if(!r.ok)throw new Error((await r.text()).trim()||"Could not load mesh source");return r.arrayBuffer()});else{++previewRequest;state.active=null;state.preview=true;render();$("#download").hidden=true;setStatus("T2MESH preview is available after automatic remeshing")}};
$("#motionSource").onchange=e=>{const item=sourceIndex.get(e.target.value);if(!item)return;$("#motion").value="";$("#motionName").textContent=item.name;void preview("motion",async()=>{const r=await fetch(`/api/sources/${encodeURIComponent(item.id)}`,{cache:"no-store"});if(!r.ok)throw new Error((await r.text()).trim()||"Could not load motion source");return r.arrayBuffer()})};
$("#giraffeInput").onclick=()=>void example("giraffe-input",false);$("#giraffeResult").onclick=()=>void example("giraffe-result",true);
$("#bind").onclick=async()=>{const form=new FormData(),mf=$("#mesh").files[0],af=$("#motion").files[0],ms=$("#meshSource").value,as=$("#motionSource").value;if(!mf&&!ms){setStatus("Choose a mesh",true);return}if(!af&&!as){setStatus("Choose a Kimodo motion",true);return}if(mf)form.append("mesh",mf);else form.append("meshSource",ms);if(af)form.append("motion",af);else form.append("motionSource",as);form.append("targetRig",$("#targetRig").value);$("#bind").disabled=true;setStatus("Uploading…");try{const job=await api("/api/bind",{method:"POST",body:form});state.job=job.id;state.active=null;state.preview=false;await refresh()}catch(e){setStatus(e.message,true)}finally{$("#bind").disabled=false}};
$("#play").onclick=()=>{viewer.playing=!viewer.playing;viewer.updateUI()};$("#rest").onclick=()=>{viewer.restPose=!viewer.restPose;viewer.updateUI()};$("#reset").onclick=()=>viewer.reset();$("#timeline").oninput=e=>{if(viewer.data){viewer.time=Number(e.target.value)*viewer.data.duration;viewer.updateUI()}};
async function start(){await sources();const requested=new URLSearchParams(location.search).get("example");if(requested&&sourceIndex.has(requested)){state.preview=true;await refresh();await example(requested,requested==="giraffe-result")}else await refresh()}
start().catch(e=>setStatus(e.message,true));
